export const PRODUCTS_SUCCES="PRODUCTS_SUCCES"
export const PRODUCTS_FAIL="PRODUCTS_FAIL"
export const PRODUCTS_ALL_SUCCES="PRODUCTS_ALL_SUCCES"
export const PRODUCTS_ALL_FAIL="PRODUCTS_ALL_FAIL"
export const PRODUCT_REQUEST="PRODUCT_REQUEST"

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_ID_SUCCES="PRODUCT_ID_SUCCES"
export const PRODUCT_ID_FAIL="PRODUCT_ID_FAIL"
export const PRODUCT_UPDATE_SUCCES="PRODUCT_UPDATE_SUCCES"

export const ADD_CART="ADD_CART"
export const DELETE_CART="DELETE_CART"
export const ADD_SHIPPING_INFO="ADD_SHIPPING_INFO"

export const CREATE_USER_SUCCES="CREATE_USER_SUCCES"
export const CREATE_USER_FAIL="CREATE_USER_FAIL"

export const LOGIN_SUCCES="LOGIN_SUCCES"
export const LOGIN_FAIL="LOGIN_FAIL"

export const USER_SUCCES="USER_SUCCES"
export const USER_FAIL="USER_FAIL"
export const ALL_USERS_SUCCES="ALL_USERS_SUCCES"
export const ALL_USERS_FAIL="ALL_USERS_FAIL"

export const USER_ID_SUCCES="USER_ID_SUCCES"
export const USER_ID_FAIL="USER_ID_FAIL"
export const REQUEST_ID_USER="REQUEST_ID_USER"

export const UPDATE_PASS_SUCCES="UPDATE_PASS_SUCCES"
export const UPDATE_USER_SUCCES="UPDATE_USER_SUCCES"

export const UPDATE_USERID_SUCCES="UPDATE_USERID_SUCCES"
export const UPDATE_USERID_FAIL="UPDATE_USERID_FAIL"

export const CREATE_PROD_SUCCES="CREATE_PROD_SUCCES"
export const UPDATE_PRODUCT_SUCCES="UPDATE_PRODUCT_SUCCES"

export const CREATE_ORDER_SUCCES="CREATE_ORDER_SUCCES"

export const GET_MY_ORDER="GET_MY_ORDER"
export const MY_ORDER_FAIL="MY_ORDER_FAIL"

export const GET_ORDER_ID="GET_ORDER_ID"
export const MY_ORDER_ID_FAIL="MY_ORDER_ID_FAIL"

export const GET_ALLORDER_SUCCES="GET_ALLORDER_SUCCES"
export const GET_ALLORDER_FAIL="GET_ALLORDER_FAIL"

export const UP_STATUS_SUCCES="UP_STATUS_SUCCES"
export const UP_STATUS_FAIL="UP_STATUS_FAIL"

export const DELETE_USER="DELETE_USER"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const DELETE_ORDER="DELETE_ORDER"

export const ADD_REVIEWS="ADD_REVIEWS"
export const GET_REVIEWS_SUCCES=" GET_REVIEWS_SUCCES"
export const GET_REVIEWS_FAIL="GET_REVIEWS_FAIL"

export const GET_SEARCH_SUCCES="GET_SEARCH_SUCCES"
export const GET_SEARCH_FAIL="GET_SEARCH_FAIL"
export const REQUEST_SEARCH="REQUEST_SEARCH"

export const PRICE_FILTER="PRICE_FILTER"

export const FORGOT_PASSWORD="FORGOT_PASSWORD"
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL"
export const RESET_PASSWORD="RESET_PASSWORD"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"

export const UP_NEW_PASSWORD="UP_NEW_PASSWORD"
export const UP_NEW_PASSWORD_FAIL="UP_NEW_PASSWORD_FAIL"

export const GOOGLE_LOGIN_SUCCES="GOOGLE_LOGIN_SUCCES"
export const GOOGLE_LOGIN_FAIL="GOOGLE_LOGIN_FAIL"
